server:
  port: 3005

postgres_url:
  url: postgres://postgres:password@localhost:5432/reddit-db-layer

redis_url:
  url: redis://:eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81@localhost:6380

logging:
  level:
    root: warn
    directives:
      - namespace: db-layer
        level: info
      - namespace: db-layer::user::listener
        level: trace
      - namespace: tower_http
        level: debug
