[package]
name = "dark-matter"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
sea-orm = "0.12.12"
uuid = { version = "1.7.0", features = ["serde", "v4"] }
chrono = { version = "0.4.32", features = ["serde"] }