server:
  port: 3005


kafka:
  broker:
    urls: localhost:9092
  consumer:
    - id: post
      topic:
        - post
      client_id: post.client.id
      group_id: post.group.id
  topic:
    mappings:
      - id: post
        topic_name: post
        partitions: 2


logging:
  level:
    root: warn
    directives:
      - namespace: aether-post
        level: info
      - namespace: aether-post::post::listener
        level: trace
      - namespace: tower_http
        level: debug


rabbit_mq:
  ampq_addr: amqp://admin:password@127.0.0.1:5672/%2f