server:
  port: 3005


kafka:
  broker:
    urls: localhost:9092
  consumer:
    - id: user
      topic:
        - user
      client_id: user.client.id
      group_id: user.group.id
  topic:
    mappings:
      - id: user
        topic_name: user
        partitions: 2


logging:
  level:
    root: warn
    directives:
      - namespace: aether-user
        level: info
      - namespace: aether-user::user::listener
        level: trace
      - namespace: tower_http
        level: debug


rabbit_mq:
  ampq_addr: amqp://admin:password@127.0.0.1:5672/%2f