server:
  port: 3005


kafka:
  broker:
    urls: localhost:9092
  consumer:
    - id: subreddit
      topic:
        - subreddit
      client_id: subreddit.client.id
      group_id: subreddit.group.id
  topic:
    mappings:
      - id: subreddit
        topic_name: subreddit
        partitions: 2


logging:
  level:
    root: warn
    directives:
      - namespace: aether-subreddit
        level: info
      - namespace: aether-subreddit::subreddit::listener
        level: trace
      - namespace: tower_http
        level: debug


rabbit_mq:
  ampq_addr: amqp://admin:password@127.0.0.1:5672/%2f